# All other settings are inherited from _default/config.toml
# This way you can run a development and production versions without rewriting the config file
baseURL = "https://hugo-html5up-alpha.nelsonroberto.com/"