# This the default config from which all other configurations inherit
## For a more detailed example of the themes capabilities look at "development/config.toml"
languageCode = "en-us"
title = "Alpha by HTML5 UP"
baseURL = "https://example.com"
theme = "hugo-html5up-alpha"
disqusShortname = ""

[params]
  description = "Another fine responsive site template freebie by HTML5 UP."
  images = ["images/pic01.jpg"]
  author = "Hugo Port: [Nelson/Roberto](https://nelsonroberto.com/)"
  copyright = "Â© Untitled. All rights reserved."
  design = "Design: [HTML5 UP](http://html5up.net/)"
  mainSections = ["blog"]

### Footer Social Media Links ###
[[params.share]]
title = "facebook"
icon = "fa-facebook-f" # fontawesome icons https://fontawesome.com/icons?d=gallery&s=brands
link = "https://www.facebook.com/"

[[params.share]]
title = "twitter"
icon = "fa-twitter"
link = "https://twitter.com/"

[[params.share]]
title = "linkedin"
icon = "fa-linkedin"
link = "https://www.linkedin.com"